name: Run unit tests
on: [push]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup node 16
              uses: actions/setup-node@v1
              with:
                  node-version: 16
            - run: npm install --no-save
            - run: npm run build
